# A simple name for your workflow
name: IITM Tools Course Action

# Controls when the action will run.
# It runs on pushes to the main branch and can also be run manually.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This is a standard first step that checks out your repository's code
      - name: Check out repository code
        uses: actions/checkout@v4

      # This is the custom step that fulfills the requirement
      - name: 22f2000647@ds.study.iitm.ac.in
        run: echo "This step is uniquely named for the course requirement."
